11 Auto-set the Decision user
christhonie/leave-application pull request #21
Opened 2021-06-02 17:03 UTC by Knoety

Second Pull request with issue #16 included

2021-06-02 17:12 UTC, christhonie requested changes

2021-06-02 17:12 UTC, christhonie commented on src/main/webapp/app/entities/decision/update/decision-update.component.ts
> +    user: [],
Haal die user property uit. Jy moet dan in updateForm en createFromForm die verwysings daarna ook verwyder.

2021-06-02 17:13 UTC, christhonie commented
Ek sien jy het die probleem ontdek om die form te probeer save.

Die user property van die edit form kan heeltemal verwyder word. Jy sal na die editForm variable in src\main\webapp\app\entities\decision\update\decision-update.component.ts moet gaan kyk, die user property verwyder en elke geval waar hy geskryf of gelees word.

Ek sal additionele comments maak waar jy aandag moet gee.

2021-06-02 17:16 UTC, christhonie requested changes

2021-06-02 17:16 UTC, christhonie commented on src/main/webapp/app/entities/decision/update/decision-update.component.ts
> +    user: [],
Verwyder ook vir my die usersSharedCollection propery in die class, die userService property (wat 'n parameter in die constructor is), verwyder die import van die userService en verwyder ook die gebruik van die userService in updateForm() en loadRelationshipsOptions().

2021-06-03 15:14 UTC, Knoety commented on src/main/webapp/app/entities/decision/update/decision-update.component.ts
> +    user: [],
Ah ekt gewonder as ek moes meer goed remove ek wou net die button laat werk asap vir more! Het die additional changes gemaak :)

2021-06-03 15:29 UTC, Knoety commented on src/main/webapp/app/entities/decision/update/decision-update.component.ts
> +    user: [],
Ek het dit weer getoets met die nuutste commit + al die suggested removals en dit laat die save button nie weer in fade nie so een van daai removals is required. Ek gaan kyk watse een veroorsaak dit en hom readd

2021-06-03 18:45 UTC, christhonie approved these changes

2021-06-03 18:47 UTC, christhonie commented
The changes committed was correct, but this caused additional bugs which were pointed out by the test cases. We will have to go over that tomorrow before training, as this code will not work 100%.

2021-06-04 09:58 UTC, christhonie requested changes
Please review the comments I have made in code.

2021-06-04 09:58 UTC, christhonie commented on src/main/webapp/app/entities/decision/update/decision-update.component.spec.ts
> -        const user: IUser = { id: 27699 };
Ethan, remove this whole "method", starting at it("Should.... (Line67) to }); (Line 71). This test has no value once you have gutted out the expect statements.

2021-06-04 10:07 UTC, christhonie approved these changes
Thanks. That is all nice and clean now. Good work.

2021-06-04 10:15 UTC, merged